# Generated by Django 4.2.5 on 2023-12-13 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Campaign name')),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField(default='http://127.0.0.1', max_length=256, verbose_name='Database host address')),
                ('dataset_path', models.CharField(default='/', max_length=256, verbose_name='Répertoire racine des datasets')),
                ('active', models.BooleanField(default=True, verbose_name='La configuration est active')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('uddate', models.DateTimeField(null=True, verbose_name='last update date')),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='(*) Nom du contexte')),
                ('code', models.CharField(max_length=64, verbose_name='(*) Code')),
                ('type', models.SmallIntegerField(choices=[(1, 'Contexte a priori'), (2, 'Contexte a posteriori')], verbose_name='(*) Type de contexte')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Device name')),
                ('type', models.CharField(max_length=64, verbose_name='Device type')),
                ('identifier', models.CharField(max_length=128, verbose_name='Device identifier')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nom local')),
                ('path', models.CharField(max_length=256, verbose_name='Chemin absolu (/data/...)')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='aidb.campaign')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='aidb.device')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Domain name')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='FileContexting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.FloatField(verbose_name='(*) Timestamp du début du contexte')),
                ('datetime_end', models.FloatField(verbose_name='(*) Timestamp de fin du context')),
                ('code', models.CharField(max_length=36, verbose_name='(*) Code unique')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidb.context')),
            ],
        ),
        migrations.CreateModel(
            name='FileLabeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.FloatField(verbose_name='(*) Timestamp du début du label')),
                ('datetime_end', models.FloatField(verbose_name='(*) Timestamp de fin du label')),
                ('code', models.CharField(max_length=36, verbose_name='(*) Code unique')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('contexts', models.ManyToManyField(blank=True, to='aidb.context')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='(*) Nom du label')),
                ('code', models.CharField(max_length=64, verbose_name='(*) Code')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='aidb.domain')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='aidb.label')),
            ],
        ),
        migrations.CreateModel(
            name='Tagcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="Nom de la catégorie d'étiquette")),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="Nom de l'étiquette")),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('tagcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='aidb.tagcat')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128, verbose_name='(*) Nom du fichier')),
                ('type', models.SmallIntegerField(choices=[(1, 'Fichier H5'), (2, 'Fichier vidéo mp4'), (3, 'Fichier son wav'), (4, 'Fichier H5 au format Mu32')], verbose_name='(*) Type de données')),
                ('datetime', models.DateTimeField(verbose_name="(*) Date et heure de l'enregistrement ")),
                ('duration', models.BigIntegerField(verbose_name="(*) Durée de l'enregistrement en microsecondes")),
                ('size', models.BigIntegerField(verbose_name='(*) Taille du fichier en octets')),
                ('integrity', models.BooleanField(null=True, verbose_name='Le fichier est valide')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('contexts', models.ManyToManyField(through='aidb.FileContexting', to='aidb.context')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='aidb.directory')),
                ('labels', models.ManyToManyField(through='aidb.FileLabeling', to='aidb.label')),
                ('tags', models.ManyToManyField(blank=True, to='aidb.tag')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='labels', to='aidb.tag'),
        ),
        migrations.AddField(
            model_name='filelabeling',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidb.label'),
        ),
        migrations.AddField(
            model_name='filelabeling',
            name='sourcefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidb.sourcefile'),
        ),
        migrations.AddField(
            model_name='filelabeling',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='filelabelings', to='aidb.tag'),
        ),
        migrations.AddField(
            model_name='filecontexting',
            name='sourcefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidb.sourcefile'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(auto_created=True, max_length=128, null=True, verbose_name='Nom du fichier de sauvegarde')),
                ('name', models.CharField(max_length=128, verbose_name='(*) Nom du dataset')),
                ('code', models.CharField(max_length=64, verbose_name='(*) Code')),
                ('comment', models.TextField(null=True, verbose_name='Notes')),
                ('info', models.JSONField(null=True, verbose_name='Infos')),
                ('crdate', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('contexts', models.ManyToManyField(blank=True, to='aidb.context')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='aidb.domain')),
                ('filelabelings', models.ManyToManyField(blank=True, to='aidb.filelabeling')),
                ('labels', models.ManyToManyField(blank=True, to='aidb.label')),
                ('tags', models.ManyToManyField(blank=True, related_name='datasets', to='aidb.tag')),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='aidb.domain'),
        ),
        migrations.AddField(
            model_name='context',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='aidb.context'),
        ),
        migrations.AddField(
            model_name='context',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contexts', to='aidb.tag'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='aidb.domain'),
        ),
    ]
